### ISSUE TITLE
Demos Subpage - Zooming is bricked in Chrome

### ISSUE THREAD

**Issue by Insax** [savetheinternetinfo/frontend#3]
Zooming is not possible on the map - most likely because we the map uses full width - therefore chrome blocks the zooming

**Comment by schrej** [comment]
No, I disabled zooming using the scrollwheel to fix scrolling on the page. You can zoom by double clicking or using the buttons.
Ideally we would have it like google maps, so you can hold CRTL to zoom using the mouse wheel.
